
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 07 07:04:24 IRDT 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 50;
  public static final int BOOL = 6;
  public static final int CONST = 17;
  public static final int BOOL_CONST = 29;
  public static final int UNTIL = 35;
  public static final int GEQ = 59;
  public static final int SIZEOF = 21;
  public static final int COMMA = 70;
  public static final int RBRACE = 73;
  public static final int DOUBLE = 10;
  public static final int LBRACE = 72;
  public static final int STRING_CONST = 30;
  public static final int NOT = 64;
  public static final int TILDE = 66;
  public static final int FLOAT = 7;
  public static final int GOTO = 44;
  public static final int RECORD = 16;
  public static final int MOD = 52;
  public static final int ISEQUAL = 56;
  public static final int REAL_CONST = 31;
  public static final int INT_TYPE = 45;
  public static final int PIPE = 54;
  public static final int SLASH = 51;
  public static final int LONG = 8;
  public static final int PLUS = 48;
  public static final int LPAR = 46;
  public static final int EQUAL = 65;
  public static final int CHAR = 9;
  public static final int INPUT = 40;
  public static final int SWITCH = 24;
  public static final int FOR = 33;
  public static final int GREATER = 61;
  public static final int VOID = 12;
  public static final int EXTERN = 2;
  public static final int RETURN = 18;
  public static final int INT_CONST = 27;
  public static final int ELSE = 23;
  public static final int BREAK = 19;
  public static final int DOT = 77;
  public static final int AMPERSAND = 53;
  public static final int INT = 5;
  public static final int EOF = 0;
  public static final int SEMICOLON = 38;
  public static final int COMMENT = 75;
  public static final int RPAR = 47;
  public static final int DEFAULT = 32;
  public static final int EXCLAM = 69;
  public static final int FUNCTION = 41;
  public static final int REPEAT = 34;
  public static final int MINUS = 49;
  public static final int OUTPUT = 42;
  public static final int IN = 37;
  public static final int OR = 63;
  public static final int error = 1;
  public static final int CHAR_CONST = 28;
  public static final int CONTINUE = 20;
  public static final int IF = 22;
  public static final int ID = 76;
  public static final int RBRAC = 4;
  public static final int MINUSMINUS = 67;
  public static final int OF = 25;
  public static final int END = 15;
  public static final int COLON = 71;
  public static final int FOREACH = 36;
  public static final int LONG_CONST = 39;
  public static final int CARET = 55;
  public static final int NOTEQUAL = 57;
  public static final int BEGIN = 14;
  public static final int CASE = 26;
  public static final int PLUSPLUS = 68;
  public static final int STRING = 11;
  public static final int LESS = 60;
  public static final int LBRAC = 3;
  public static final int AND = 62;
  public static final int UMINUS = 74;
  public static final int STATIC = 43;
  public static final int AUTO = 13;
  public static final int LEQ = 58;
}

